name: pkg.pr.new publish
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          # eslint-plugin-jsdoc requires node ^22.13.0 || >=24
          node-version: 22

      - run: yarn --frozen-lockfile --ignore-engines

      - run: yarn tsc

      - run: npx pkg-pr-new publish
